### PR TITLE
v1.3.1

### PR DESCRIPTION
**Pull request by yourmnbbn**
## Changes
- Fix steamclient library signature lookup failure in some platforms.
- Use direct steamwork api instead of raw symbol to get necessary information.

### CODE REVIEW

**Comment by yourmnbbn** [comment]
@daffyyyy Have you done any modifications to the extension? The extension is not using IGameConfig interface to get steamclient library signature lookup result because sourcemod officially only support `engine`, `server` and `matchmaking_ds` library. This error doesn't make sense with the extension, you can even remove `"library"  "steamclient"` keyvalue in gamedata, it stays there just to remind everyone that the signature is from the steamclient library.

**Comment by yourmnbbn** [comment]
@daffyyyy I haven't noticed the errorlog, just ignore this, everything is fine. It just doesn't recognize the steamclient library so it throws this error. However the extension is reparsing the gameconfig by ITestParser interface to do the signature scanning. If you are bothered by this error spamming you can just change each `"library" "steamclient"` in gamedata to `"library" "engine"` or `"library" "server"`, it doesn't matter.

**Comment by daffyyyy** [comment]
> @daffyyyy I haven't noticed the errorlog, just ignore this, everything is fine. It just doesn't recognize the steamclient library so it throws this error. However the extension is reparsing the gameconfig by ITestParser interface to do the signature scanning. If you are bothered by this error spamming you can just change each `"library" "steamclient"` in gamedata to `"library" "engine"` or `"library" "server"`, it doesn't matter.

Maybe sm <= 1.10 throw errorlog ;) I guess you are testing it on a different version or 1.11

**Comment by yourmnbbn** [comment]
@daffyyyy I’m using sm1.10 either. But I didn’t check the error log. I’m testing this extension via python script since it’s all about the query, don’t care much about the error log. Maybe it’s worth a fix to this error spamming. But it doesn’t matter at all, the extension is working fine, it’s just sourcemod game config implementation will throw errors to all the unsupported library.

**Pull request merged**
